### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/catalog-of-my-things-ruby-capstone#34]
### GitHub Project Link:
https://github.com/topeogunleye/catalog-of-my-things-ruby-capstone/projects/2

There are 3 people on this team.

### Team members as assigned to tasks listed:
Team member #1: @topeogunleye 
Team member #2: @afizsavage 
Team member #3: @blessedjasonmwanza

**Comment by rloterh** [comment]
Hi Team, 

Great job for making the necessary changes recommended by the previous reviewer. However, there's always room for improvement.
Kindly consider my OPTIONAL comments

## Optional suggestions
_Please keep in mind that you, for best practices and following the project requirements and the design templates closely kindly consider these aspects as outlined in the below comments._

- [ ] OPTIONAL
Over 15 of your tasks do not have any description attached. Kindly endeavor to improve this aspect
![image](https://user-images.githubusercontent.com/12745474/160593753-863405b8-46de-4519-97f6-e3fc65d5b7fa.png)
![image](https://user-images.githubusercontent.com/12745474/160593850-d63aa137-2bcd-4962-b87d-84d4a0f32614.png)
![image](https://user-images.githubusercontent.com/12745474/160593957-b145d93e-dc71-49bf-9f8a-14d1b617e83d.png)

**_Kindly notice that these are required changes, I'm sorry they didn't show up in the earlier review._**


<br>
Your project is complete! Congratulations! 🥂There is nothing else to say other than... it's time to merge it 👍.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
